/**
 * @file gui_event_handlers.c
 * @authors mebblera@student.21-school.ru
 * @authors weaveryu@student.21-school.ru
 * @brief
 * Functions to handle events, generated by widgets from 3DViewer UI. Widgets
 * initialised in gui_main.c sourcefile.
 * @copyright Copyright (c) 2023
 * TODO: adjust on release
 */

#include <gdk/gdkkeysyms.h>
#include "gui_main.h"

void on_btn_pressed_hide_ctrl(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  if (gtk_widget_get_visible(p_ctrl->box_ctrls)) {
    gtk_widget_set_visible(p_ctrl->box_ctrls, FALSE);
    gtk_button_set_label(button, "Show controls");
  } else {
    gtk_widget_set_visible(p_ctrl->box_ctrls, TRUE);
    gtk_button_set_label(button, "Hide controls");
  }
}

void on_btn_pressed_help(GtkButton *button, gpointer user_data) {
  widgets_core *p_core = user_data;
  gtk_widget_show_all(p_core->window_help);
}

gboolean on_key_press(
    GtkWidget *widget, GdkEventKey *event, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  GtkWidget *target;
  uint key = event->keyval;
  gboolean ctrl_pressed = (gboolean) (event->state & GDK_CONTROL_MASK);
  printf("Pressed key: %d\n", event->keyval);
  if (key == GDK_KEY_Return) {
    target = gtk_window_get_focus(GTK_WINDOW(widget));
    if (target == GTK_WIDGET(p_ctrl->e_trans_x)) {
      set_adjustment_from_entry(p_ctrl->e_trans_x, p_ctrl->adj_trans_x);
    } else if (target == GTK_WIDGET(p_ctrl->e_trans_y)) {
      set_adjustment_from_entry(p_ctrl->e_trans_y, p_ctrl->adj_trans_y);
    } else if (target == GTK_WIDGET(p_ctrl->e_trans_z)) {
      set_adjustment_from_entry(p_ctrl->e_trans_z, p_ctrl->adj_trans_z);
    } else if (target == GTK_WIDGET(p_ctrl->e_rotat_x)) {
      set_adjustment_from_entry(p_ctrl->e_rotat_x, p_ctrl->adj_rotat_x);
    } else if (target == GTK_WIDGET(p_ctrl->e_rotat_y)) {
      set_adjustment_from_entry(p_ctrl->e_rotat_y, p_ctrl->adj_rotat_y);
    } else if (target == GTK_WIDGET(p_ctrl->e_rotat_z)) {
      set_adjustment_from_entry(p_ctrl->e_rotat_z, p_ctrl->adj_rotat_z);
    } else if (target == GTK_WIDGET(p_ctrl->e_scale)) {
      set_adjustment_from_entry(p_ctrl->e_scale, p_ctrl->adj_scale);
    }
  } else if (is_key(key, 'A')) {
    ctrl_pressed ?
                 on_btn_pressed_b_rotat_x_l(NULL, p_ctrl) :
                 on_btn_pressed_b_trans_x_l(NULL, p_ctrl);
  } else if (is_key(key, 'D')) {
    ctrl_pressed ?
                 on_btn_pressed_b_rotat_x_r(NULL, p_ctrl) :
                 on_btn_pressed_b_trans_x_r(NULL, p_ctrl);
  } else if (is_key(key, 'S')) {
    ctrl_pressed ?
                 on_btn_pressed_b_rotat_y_l(NULL, p_ctrl) :
                 on_btn_pressed_b_trans_y_l(NULL, p_ctrl);
  } else if (is_key(key, 'W')) {
    ctrl_pressed ?
                 on_btn_pressed_b_rotat_y_r(NULL, p_ctrl) :
                 on_btn_pressed_b_trans_y_r(NULL, p_ctrl);
  } else if (is_key(key, 'Q')) {
    ctrl_pressed ?
                 on_btn_pressed_b_rotat_z_l(NULL, p_ctrl) :
                 on_btn_pressed_b_trans_z_l(NULL, p_ctrl);
  } else if (is_key(key, 'E')) {
    ctrl_pressed ?
                 on_btn_pressed_b_rotat_z_r(NULL, p_ctrl) :
                 on_btn_pressed_b_trans_z_r(NULL, p_ctrl);
  } else if (is_key(key, '-')) {
    on_btn_pressed_b_scale_l(NULL, p_ctrl);
  } else if (is_key(key, '+')) {
    on_btn_pressed_b_scale_r(NULL, p_ctrl);
  }
  return FALSE;
}

void on_adj_trans_changed(GtkAdjustment *adj, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  set_entry_from_adjust(p_ctrl->e_trans_x, p_ctrl->adj_trans_x);
  set_entry_from_adjust(p_ctrl->e_trans_y, p_ctrl->adj_trans_y);
  set_entry_from_adjust(p_ctrl->e_trans_z, p_ctrl->adj_trans_z);
}


void on_adj_rotat_changed(GtkAdjustment *adj, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  set_entry_from_adjust(p_ctrl->e_rotat_x, p_ctrl->adj_rotat_x);
  set_entry_from_adjust(p_ctrl->e_rotat_y, p_ctrl->adj_rotat_y);
  set_entry_from_adjust(p_ctrl->e_rotat_z, p_ctrl->adj_rotat_z);
}

void on_adj_scale_changed(GtkAdjustment *adj, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  set_entry_from_adjust(p_ctrl->e_scale, p_ctrl->adj_scale);
}

void on_btn_pressed_b_trans_x_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_trans_x, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_trans_x_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_trans_x, INC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_trans_y_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_trans_y, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_trans_y_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_trans_y, INC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_trans_z_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_trans_z, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_trans_z_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_trans_z, INC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_rotat_x_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_rotat_x, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_rotat_x_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_rotat_x, INC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_rotat_y_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_rotat_y, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_rotat_y_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_rotat_y, INC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_rotat_z_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_rotat_z, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_rotat_z_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_rotat_z, INC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_scale_l(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_scale, DEC_MUL, CTRL_MUL);
}

void on_btn_pressed_b_scale_r(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  shift_adjustment(p_ctrl->adj_scale, INC_MUL, CTRL_MUL);
}

