/**
 * @file gui_event_handlers.c
 * @authors mebblera@student.21-school.ru
 * @authors weaveryu@student.21-school.ru
 * @brief
 * Functions to handle events, generated by widgets from 3DViewer UI. Widgets
 * initialised in gui_main.c sourcefile.
 * @copyright Copyright (c) 2023
 * TODO: adjust on release
 */

#include "gui_main.h"

void on_btn_pressed_hide_ctrl(GtkButton *button, gpointer user_data) {
  widgets_controls *p_ctrl = user_data;
  if (gtk_widget_get_visible(p_ctrl->box_ctrls)) {
    gtk_widget_set_visible(p_ctrl->box_ctrls, FALSE);
    gtk_button_set_label(button, "Show controls");
  } else {
    gtk_widget_set_visible(p_ctrl->box_ctrls, TRUE);
    gtk_button_set_label(button, "Hide controls");
  }
}
